tslib: patch for version 1.22
HED-Inc/tslib pull request #1
Opened 2022-07-15 07:38 UTC by EIC-RahulMoorkath

PR raised for Buildroot 2022.02.1 changes. This patch is common for both CL711 and CL713 products.

2022-07-15 12:40 UTC, HED-mstarr requested changes
I think there was a misunderstanding.  I didn't want the patch file checked in.  I wanted the changes from the patch file applied to the source as it's own commit.  This should allow us to recreate the patch.

2022-07-18 07:39 UTC, EIC-RahulMoorkath commented
> I think there was a misunderstanding. I didn't want the patch file checked in. I wanted the changes from the patch file applied to the source as it's own commit. This should allow us to recreate the patch.

Sorry for that. I have pushed source code changes again.

2022-07-18 20:56 UTC, HED-djahnke approved these changes

2022-07-20 03:05 UTC, HED-djahnke approved these changes

2022-07-20 03:59 UTC, HED-mstarr approved these changes

2022-07-20 04:00 UTC, merged